# Dictionary mapping keywords to sectors and companies
keyword_mapping = {
    'sectors': {
        # Existing sectors
        'energy': ['XOM', 'CVX', 'COP', 'EOG', 'SHEL', 'BP', 'EQNR', 'TTE', 'PSX', 'VLO'],
        'banking': ['JPM', 'BAC', 'WFC', 'C', 'GS', 'MS', 'USB', 'PNC', 'TFC', 'UBS'],
        'electric vehicles': ['TSLA', 'NIO', 'LI', 'XPEV', 'LCID', 'RIVN', 'NKLA', 'FSR', 'AYRO', 'GOEV'],
        'automobiles': ['TSLA', 'GM', 'F', 'TM', 'HMC', 'BMWYY', 'DDAIF', 'VWAGY', 'RACE', 'NSANY'],
        'tech': ['AAPL', 'GOOGL', 'MSFT', 'NVDA', 'TSM', 'META', 'ADBE', 'CRM', 'INTC', 'ORCL'],
        'software': ['MSFT', 'ADBE', 'CRM', 'INTU', 'NOW', 'SNOW', 'TEAM', 'DDOG', 'SPLK', 'MDB'],
        'hardware': ['AAPL', 'DELL', 'HPQ', 'IBM', 'CSCO', 'INTC', 'AMD', 'NVIDIA', 'DE', 'ORCL'],
        'semiconductors': ['NVDA', 'TSM', 'INTC', 'AMD', 'ASML', 'QCOM', 'TXN', 'AVGO', 'MU', 'AMAT'],
        'cloud computing': ['AMZN', 'MSFT', 'GOOGL', 'ORCL', 'IBM', 'CRM', 'SNOW', 'DDOG', 'DOCN', 'NET'],
        'ecommerce': ['AMZN', 'BABA', 'SHOP', 'JD', 'MELI', 'EBAY', 'WMT', 'TGT', 'PDD', 'SE'],
        'social media': ['META', 'TWTR', 'SNAP', 'PINS', 'BIDU', 'WB', 'TME', 'SPOT', 'MTCH', 'YY'],
        'healthcare': ['JNJ', 'PFE', 'MRK', 'ABBV', 'LLY', 'BMY', 'GILD', 'AZN', 'REGN', 'VRTX'],
        'biotech': ['MRNA', 'AMGN', 'BIIB', 'GILD', 'VRTX', 'REGN', 'ILMN', 'ALNY', 'EXEL', 'CRSP'],
        'pharmaceuticals': ['PFE', 'MRK', 'JNJ', 'ABBV', 'LLY', 'BMY', 'AZN', 'GSK', 'SNY', 'NVS'],
        'consumer goods': ['PG', 'KO', 'PEP', 'PM', 'UL', 'CL', 'MNST', 'KHC', 'MDLZ', 'DEO'],
        'retail': ['WMT', 'TGT', 'HD', 'LOW', 'COST', 'KR', 'DG', 'DLTR', 'BBY', 'ROST'],
        'aerospace': ['BA', 'RTX', 'NOC', 'LMT', 'GD', 'LHX', 'TDY', 'HII', 'TXT', 'SPR'],
        'defense': ['LMT', 'NOC', 'RTX', 'GD', 'BA', 'LHX', 'HII', 'TXT', 'LMT', 'TDY'],
        'telecom': ['VZ', 'T', 'TMUS', 'CMCSA', 'CHTR', 'DISH', 'VOD', 'ORAN', 'AMX', 'TEF'],
        'utilities': ['NEE', 'DUK', 'SO', 'AEP', 'EXC', 'SRE', 'D', 'PEG', 'ED', 'XEL'],
        'transportation': ['UPS', 'FDX', 'DAL', 'LUV', 'UAL', 'CSX', 'NSC', 'UNP', 'JBHT', 'KSU'],
        'food and beverage': ['KO', 'PEP', 'MDLZ', 'KHC', 'GIS', 'KDP', 'SYY', 'TSN', 'BF.B', 'CPB'],
        'real estate': ['AMT', 'PLD', 'EQIX', 'SPG', 'PSA', 'DLR', 'SBAC', 'WELL', 'ARE', 'AVB'],
        'insurance': ['BRK.B', 'AIG', 'ALL', 'PGR', 'MET', 'TRV', 'PRU', 'LNC', 'CINF', 'HIG'],
        'logistics': ['UPS', 'FDX', 'XPO', 'JBHT', 'CHRW', 'EXPD', 'KNIN.SW', 'ZTO', 'R', 'TFII.TO'],
        'renewable energy': ['NEE', 'ENPH', 'SEDG', 'FSLR', 'RUN', 'VWS.CO', 'TSLA', 'BEPC', 'CWEN', 'PLUG'],
        'industrial goods': ['CAT', 'DE', 'MMM', 'HON', 'ETN', 'EMR', 'GE', 'ITW', 'ROK', 'PH'],
        'metals and mining': ['BHP', 'VALE', 'RIO', 'FCX', 'NEM', 'SCCO', 'TECK', 'GOLD', 'AA', 'NUE'],
        'financial services': ['V', 'MA', 'PYPL', 'AXP', 'SQ', 'DFS', 'ALLY', 'WEX', 'COF', 'SYF'],
        'media': ['DIS', 'NFLX', 'CMCSA', 'T', 'DISCA', 'FOX', 'NWS', 'VIAC', 'RBLX', 'PARA'],
        'construction': ['LEN', 'PHM', 'DHI', 'NVR', 'TOL', 'MTH', 'KBH', 'BZH', 'GRBK', 'TMHC'],
        'oil': ['XOM', 'CVX', 'COP', 'EOG', 'OXY', 'PSX', 'VLO', 'MPC', 'HES', 'PXD'],

        # New sectors
        'neurotech': ['NURO', 'BCYC', 'SAGE', 'BOLD', 'VERV', 'NEO', 'TMDX', 'MDT', 'STXS', 'RGLS'],
        'genomics': ['ILMN', 'CRSP', 'EDIT', 'NTLA', 'PACB', 'TWST', 'BEAM', 'VRTX', 'NVTA'],
        'xr': ['META', 'AAPL', 'GOOGL', 'MSFT', 'SONY', 'VUZI', 'MRVSF', 'U'],
        'quantum': ['IBM', 'GOOGL', 'MSFT', 'RIGL', 'IONQ', 'QSI', 'BB', 'RTX', 'NVDA', 'AQT'],
        
        # Separate subcategories for AR/VR/MR/XR
        'vr': ['META', 'SONY', 'HTC', 'AAPL', 'GOOGL', 'RBLX', 'VUZI', 'PICO'],  # Pure VR companies
        'ar': ['MSFT', 'GOOGL', 'VUZI', 'MAGIC LEAP', 'SNAP', 'NEXCF'],  # Pure AR companies
        'mr': ['MSFT', 'META', 'GOOGL', 'HTC', 'SONY'],  # Mixed Reality (HoloLens, Magic Leap)
        'bci': ['NURO', 'BCYC', 'SAGE', 'NEO', 'STXS', 'RGLS'],  # Brain-Computer Interface (narrower than Neurotech)
        'bmi': ['MDT', 'TMDX', 'STXS'],  # Brain-Machine Interface (distinct but related to BCI)

        # Aliases for new sectors
        'dna': ['ILMN', 'CRSP', 'EDIT', 'NTLA', 'PACB', 'TWST', 'BEAM', 'VRTX', 'NVTA'],  # Genomics/Bioinformatics
        'bioinformatics': ['ILMN', 'CRSP', 'EDIT', 'NTLA', 'PACB', 'TWST', 'BEAM', 'VRTX', 'NVTA'],
        'xr': ['META', 'AAPL', 'GOOGL', 'MSFT', 'SONY', 'VUZI', 'RBLX', 'MRVSF'],  # XR (Extended Reality)
        'q': ['IBM', 'GOOGL', 'MSFT', 'RIGL', 'IONQ', 'QSI', 'BB', 'RTX', 'NVDA', 'AQT'],  # Quantum Computing
    },

    'currencies': {
        'usd': 'USD',
        'dollar': 'USD', 
        'eur': 'EUR', 
        'euro': 'EUR',
        'gbp': 'GBP', 
        'pound': 'GBP',
        'jpy': 'JPY',
        'yen': 'JPY',
        'aud': 'AUD', 
        'cad': 'CAD', 
        'chf': 'CHF', 
        'cny': 'CNY',
        'hkd': 'HKD', 
        'nzd': 'NZD', 
        'sek': 'SEK', 
        'krw': 'KRW',
        'sgd': 'SGD', 
        'nok': 'NOK', 
        'mxn': 'MXN', 
        'inr': 'INR',
        'rub': 'RUB',
        'ruble': 'RUB', 
        'brl': 'BRL', 
        'zar': 'ZAR', 
        'try': 'TRY'
    },
    'cryptocurrencies': {
        'btc': 'BTC-USD', 
        'bitcoin': 'BTC-USD', 
        'eth': 'ETH-USD', 
        'ethereum': 'ETH-USD',
        'degen': 'DEGEN30096-USD',
        'ether': 'ETH-USD',  
        'bnb': 'BNB-USD',
        'usdt': 'USDT-USD', 
        'ada': 'ADA-USD', 
        'sol': 'SOL-USD',
        'xrp': 'XRP-USD', 
        'doge': 'DOGE-USD', 
        'dot': 'DOT-USD',
        'matic': 'MATIC-USD', 
        'ltc': 'LTC-USD',
        'litecoin': 'LTC-USD',
        'uni': 'UNI-USD',
        'avax': 'AVAX-USD', 
        'shib': 'SHIB-USD', 
        'busd': 'BUSD-USD',
        'trx': 'TRX-USD', 
        'link': 'LINK-USD', 
        'atom': 'ATOM-USD',
        'xmr': 'XMR-USD', 
        'ftm': 'FTM-USD'
    },

    # Expanded company dictionary with aliases
    'companies': {
        # Existing companies with aliases
        'tesla': 'TSLA',
        'tsla': 'TSLA',
        'nio': 'NIO',
        'shell': 'SHEL',
        'shel': 'SHEL',
        'bp': 'BP',
        'saudi aramco': '2222.SR',
        'aramco': '2222.SR',
        '2222': '2222.SR',
        'equinor': 'EQNR',
        'eqnr': 'EQNR',
        'total': 'TTE',
        'total energies': 'TTE',
        'tte' : 'TTE',
        'jpm': 'JPM',
        'chase': 'JPM',
        'JP Morgan': 'JPM',
        'JP Morgans': 'JPM',
        'ubs': 'UBS',
        'boa': 'BAC',
        'bank of america': 'BAC',
        'bac' : 'BAC',
        'lucid motors': 'LCID',
        'lucid' : 'LCID',
        'lcid' : 'LCID',
        'apple': 'AAPL',
        'aapl': 'AAPL',
        'google': 'GOOGL',
        'alphabet': 'GOOGL',
        'google': 'GOOGL',
        'msft': 'MSFT',
        'microsoft': 'MSFT',
        'meta': 'META',
        'facebook': 'META',
        'ibm': 'IBM',
        'intel': 'INTC',
        'intc' : 'INTC',
        'nvda': 'NVDA',
        'nvidia': 'NVDA',
        'amazon': 'AMZN',
        'amzn': 'AMZN',
        'sony': 'SONY',
        'htc': 'HTC',
        'roblox': 'RBLX',
        'rblx' : 'RBLX',
        'unity': 'U',
        'u' : 'U',
        'vuzi': 'VUZI',
        'rigetti': 'RIGL',
        'rigl': 'RIGL',
        'ionq': 'IONQ',
        'blackberry': 'BB',
        'bb': 'BB',
        'lockheed': 'LMT',
        'lockheed martin': 'LMT',
        'lockheed martins': 'LMT',
        'lmt': 'LMT',
        'boeing': 'BA',
        'boeing defense': 'BA',
        'ba' : 'BA',
        'northrop grumman': 'NOC',
        'northrop' : 'NOC',
        'noc': 'NOC',
        'raytheon': 'RTX',
        'rtx': 'RTX',
        'goldman sachs': 'GS',
        'gs' : 'GS',
        'morgan stanley': 'MS',
        'ms': 'MS',
        'pnc': 'PNC',
        'wells fargo': 'WFC',
        'wfc': 'WFC',
        'citi': 'C',
        'citibank': 'C',
        'lennar': 'LEN',
        'pultegroup': 'PHM',
        'd.r. horton': 'DHI',

        # Neurotech
        'neurometrix': 'NURO',
        'nuro': 'NURO',  
        'bicycle therapeutics': 'BCYC',
        'bicycle': 'BCYC',  
        'sage therapeutics': 'SAGE',
        'sage': 'SAGE',  
        'audentes therapeutics': 'BOLD',
        'audentes': 'BOLD',  
        'bold': 'BOLD',  
        'verve therapeutics': 'VERV',
        'verve': 'VERV',  
        'neogenomics': 'NEO',
        'neo': 'NEO',  
        'transmedics group': 'TMDX',
        'transmedics': 'TMDX',  
        'medtronic': 'MDT',
        'medtronic plc': 'MDT',  
        'stereotaxis': 'STXS',
        'stereotaxis inc': 'STXS',  
        'regulus therapeutics': 'RGLS',
        'regulus': 'RGLS',  

        # Genomics
        'illumina': 'ILMN',
        'illumina inc': 'ILMN',  
        'crispr': 'CRSP',
        'crispr therapeutics': 'CRSP',  
        'editas': 'EDIT',
        'editas medicine': 'EDIT',  
        'intellia': 'NTLA',
        'intellia therapeutics': 'NTLA',  
        'pacific biosciences': 'PACB',
        'pacb': 'PACB',  
        'twist bioscience': 'TWST',
        'twist': 'TWST',  
        'beam therapeutics': 'BEAM',
        'beam': 'BEAM',  
        'vertex': 'VRTX',
        'vertex pharmaceuticals': 'VRTX',  
        'invitae': 'NVTA',
        'invitae corporation': 'NVTA',  

        # Quantum
        'rigetti': 'RIGL',
        'rigetti computing': 'RIGL',  
        'ionq': 'IONQ',
        'ionq inc': 'IONQ',  
        'quantumscape': 'QS',
        'quantumscape corporation': 'QS',  
        'quantinuum': 'QSI',
        'quantinuum technologies': 'QSI',  
        'honeywell quantum': 'QSI',
        'honeywell': 'QSI',  
        'aqt': 'AQT',
        'aqt inc': 'AQT',  
    }
}