blank_issues_enabled: false

contact_links:
  - name: ARPA technical contact
    url: mailto:input@arpacorp.net
    about: General questions about contributing or using OPSIE outside of a GitHub issue.
